# Generated by Django 5.2.8 on 2025-11-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="backup_power",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="fibre_internet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="flatlet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="garages",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="house",
            name="garden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="parking",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="house",
            name="pet_friendly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="saved_for_later",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="study",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="bathrooms",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
