# Generated by Django 5.2.7 on 2025-11-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_house_backup_power_house_fibre_internet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="backup_power",
        ),
        migrations.RemoveField(
            model_name="house",
            name="location",
        ),
        migrations.RemoveField(
            model_name="house",
            name="pet_friendly",
        ),
        migrations.RemoveField(
            model_name="house",
            name="saved_for_later",
        ),
        migrations.RemoveField(
            model_name="house",
            name="square_feet",
        ),
        migrations.AddField(
            model_name="house",
            name="backup_battery",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="bathrooms",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="fibre_internet",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="flatlet",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="garages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="garden",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="parking",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="pool",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="study",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
