# Generated by Django 5.2.7 on 2025-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_remove_house_backup_power_remove_house_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="backup_battery",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="bathrooms",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="bedrooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="fibre_internet",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="flatlet",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="garden",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="pool",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="house",
            name="study",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
