# Generated by Django 5.2.8 on 2025-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_house_location_alter_house_backup_battery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="backup_battery",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="bathrooms",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="house",
            name="bedrooms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(default="No description provided"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="house",
            name="fibre_internet",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="flatlet",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="garages",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="house",
            name="garden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="location",
            field=models.CharField(default="No description provided", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="house",
            name="parking",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="house",
            name="pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="house",
            name="study",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
