# Generated by Django 5.2.7 on 2025-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0005_alter_house_backup_battery_alter_house_bathrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="bathrooms",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="house",
            name="bedrooms",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="house",
            name="garages",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="house",
            name="parking",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="house",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
