# Generated by Django 5.2.7 on 2025-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0006_alter_house_bathrooms_alter_house_bedrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Apartment", "Apartment"),
                    ("Flat", "Flat"),
                ],
                default="House",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="house",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
