# Generated by Django 5.2.8 on 2025-11-17 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_house_property_type_alter_house_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='backup_battery',
        ),
        migrations.RemoveField(
            model_name='house',
            name='fibre_internet',
        ),
        migrations.RemoveField(
            model_name='house',
            name='flatlet',
        ),
        migrations.RemoveField(
            model_name='house',
            name='garages',
        ),
        migrations.RemoveField(
            model_name='house',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='house',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='house',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='house',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='house',
            name='study',
        ),
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(default='Welcome to a landmark residence in the heart of Waterfall Estate, a home that redefines elegance, \nwhere architectural mastery, bespoke finishes, and uncompromising design converge to deliver a living experience beyond compare. \nThis newly built, architect-designed masterpiece offers five expansive, all-en-suite bedrooms, each curated as a private sanctuary of comfort, light, and space. \nFrom imported bathroom fittings to tailored wardrobe systems and floor-to-ceiling windows, every suite offers privacy, peace, and refinement, whether for family, guests, or discerning residents with a taste for the exceptional. \nThe home opens into a breathtaking double-volume entrance hall, leading into an expansive open-plan living area where seamless indoor-outdoor integration is central to the design philosophy. \nDramatic ceiling heights and full-height glass allow natural light to flood every corner, highlighting the clean lines, rich textures, and exquisite detailing throughout. \nThe living and dining spaces are designed for effortless entertaining, flowing directly onto the covered patio, a landscaped garden, and a pristine pool that feels like your own private resort. \nAt the centre of this luxurious home lies a state-of-the-art designer kitchen, custom-fitted with premium built-in appliances, striking stone countertops, soft-close cabinetry, a walk-in scullery, and a separate pantry. \nIt is both a showpiece and a working culinary space, crafted to meet the needs of a true gourmet. \nFor quieter moments, retreat to the private cinema room, acoustically designed and ready for immersive movie nights. \nA contemporary feature fireplace anchors the formal lounge, creating an intimate ambiance on cooler evenings. \nThe home also includes a dedicated home office or study, perfect for executive living or hybrid working in absolute comfort. \nStep outside and experience a fully landscaped garden, designed to evolve and mature into a tranquil green sanctuary. \nThe entertainment terrace is finished with an integrated braai area and overlooks the shimmering swimming pool, ideal for summer entertaining or year-round relaxation. \nFour oversized garages with automated doors provide ample space for luxury vehicles, recreational gear, and storage, \nwhile additional off-street parking ensures hosting guests is effortless. \nA sophisticated back-up power system guarantees uninterrupted living, with smart home infrastructure and high-speed connectivity built into every level of the home.'),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(default='Waterfall Estate, Midrand', max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(default='Price on request', max_length=50),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(default='Waterfall Estate Residence', max_length=200),
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bedrooms', 'Bedrooms'), ('Bathrooms', 'Bathrooms'), ('Kitchen', 'Kitchen'), ('Living', 'Living'), ('Exterior', 'Exterior'), ('Other', 'Other')], max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house')),
            ],
        ),
    ]
