# Generated by Django 5.2.8 on 2025-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_remove_house_backup_battery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(default='Your full house description here...'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
